"""remove sex and race columns

Revision ID: cc43c2c5084d
Revises: b1f269323ebd
Create Date: 2025-07-15 15:05:45.672328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc43c2c5084d'
down_revision: Union[str, Sequence[str], None] = 'b1f269323ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'race')
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('race', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
